In [1]:
import numpy as np

In [6]:
# numpy means numerical python. it is essential for machine learning, deep learning, computer vision , NLP etc. the converts all the data like video, audio, image or any text file into the arrrays and matrix and then the computation will be occureed on it.

In [7]:
# NumPy is an open-source Python library that facilitates efficient numerical operations on large quantities of data. 

In [8]:
l = [1,2,3,4]

In [11]:
np.array(l)

array([1, 2, 3, 4])

In [12]:
ar = np.array(l)

In [13]:
ar

array([1, 2, 3, 4])

In [18]:
# here is one sqare bracket means it is a 1d array

In [19]:
type(ar)

numpy.ndarray

In [20]:
# "ndarray" means n dimensional array.

In [21]:
# a colorfull image is a 3 dimensional array in rgb layer

In [26]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [27]:
# at above there is two square bracket theree be 2d array

In [28]:
np.asarray(l)

array([1, 2, 3, 4])

In [29]:
a= [2,3,4]

In [30]:
np.asanyarray(a)

array([2, 3, 4])

In [31]:
# array, asarray,asanyarray all can make an arrray.

In [32]:
# a matrix is a bydefault 2d array and it issubset of array . it performs all the operation that an arraycan performs.

In [33]:
b = np.matrix(l)

In [34]:
b

matrix([[1, 2, 3, 4]])

In [35]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [36]:
a = np.array(l)

In [37]:
a


array([1, 2, 3, 4])

In [38]:
c = a  

In [39]:
c

array([1, 2, 3, 4])

In [40]:
a

array([1, 2, 3, 4])

In [41]:
c[0] = 100

In [42]:
c

array([100,   2,   3,   4])

In [43]:
a

array([100,   2,   3,   4])

In [45]:
# "c" is swallow copy of "a" means any change in "a" can be seen in "c" also. i.e. data of both the "a"  and "c" are on the same location.

In [46]:
d = np.copy(a)

In [56]:
d

array([100,   2,   3,   4])

In [57]:
a

array([100, 400,   3,   4])

In [58]:
a[1] = 400

In [59]:
a

array([100, 400,   3,   4])

In [60]:
d

array([100,   2,   3,   4])

In [61]:
# Means "d" is deep copy of "a" i.e. any change of "d" can't be seen in "a" or ice-versa. as they store the data at the different locations.

In [62]:
np.fromfunction(lambda i, j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
# np.fromfunction() :-it generates the data on the basis of functions that we have applied inside it

In [64]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [68]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [69]:
iterable = (i*i for i in range(5))

In [70]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [71]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [72]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

In [73]:
#Numpy - Data Types.

In [74]:
l = [2,3,4,5,6]

In [75]:
ar = np.array(l)

In [76]:
ar

array([2, 3, 4, 5, 6])

In [77]:
ar.ndim

1

In [78]:
# means "ar" has 1 dimension


In [79]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [80]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [86]:
ar2.ndim

2

In [87]:
ar.size

5

In [88]:
ar2.size

8

In [89]:
ar

array([2, 3, 4, 5, 6])

In [90]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [91]:
ar.shape

(5,)

In [92]:
# means 1 row and 5 columns

In [93]:
ar2.shape

(2, 4)

In [94]:
# means two rows and 4 columns.

In [95]:
ar.dtype

dtype('int64')

In [96]:
ar2.dtype


dtype('int64')

In [97]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [98]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [99]:
ar22.dtype

dtype('float64')

In [100]:
list(range(5))

[0, 1, 2, 3, 4]

In [101]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [102]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [103]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [104]:
# measn here is jump of .3 from starting to the end.

In [105]:
np.linspace(1,5,10)
# here it will give 10 elements from 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [106]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [107]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
np.zeros((3,4,2))
# it will make three matrix each of (4*2)
# and is 3d.

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [117]:
ar4 = np.zeros((3,4,2,3))
# it will give 3 matrix eac is 4d and of (2*3)

In [118]:
ar4.ndim


4

In [119]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [120]:
# 3d array are used in computer vision and deeep learning

In [121]:
np.ones(4)

array([1., 1., 1., 1.])

In [122]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [123]:
on =np.ones((2,3,2))

In [124]:
on + 5


array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [125]:
on *4


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [126]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [127]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [128]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [129]:
# "means 20 elements from 2 to 4"

In [147]:
np.logspace(2,5 , 10)
# it took 10 elements with base as 10 of log

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [148]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [149]:
np.random.randn(3,4)

array([[ 1.54853516, -0.60995432,  0.64246194, -0.18656358],
       [-0.12021288,  1.85938636, -0.93396826, -0.74244505],
       [ 0.71804354,  0.34163994, -0.90004156, -0.12368026]])

In [150]:
arr = np.random.randn(3,4)

In [151]:
!pip install pandas

In [152]:
import pandas as pd 

In [153]:
pd.DataFrame(arr)
# here the arrays "arr" will be converted into the dataframe.

0         1         2         3
0  0.698746  1.014845 -0.284914  0.356714
1  0.418848 -1.414290 -0.098720  0.944262
2  0.638467 -0.792319 -0.234599 -1.149595

In [154]:
np.random.rand(3,4)
# it will produce the random data.

array([[0.96705287, 0.39060904, 0.15969185, 0.9828264 ],
       [0.19934683, 0.62226512, 0.80545415, 0.08853453],
       [0.60389656, 0.99688466, 0.97367451, 0.84794012]])

In [157]:
# random.randn() , it will give data of standard normal distribution means here mean is "0" and the thestandard deviation is 1. 
# which is not in the random.rand and the random.randint.
# In the random.randint the output isonly integers.

In [159]:
pd.DataFrame(np.random.randint(1,110 , (300,400)))
# it will give a (300*400 matrix) with values from 1 to 110 and are only integers

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0    108   77   98  104   99   50   28   40   23   76  ...   61   93   60   
1     53    2   36   39  108   59   79   42   58   52  ...   70   58   55   
2     31  103   50  102   24   91   73    6  103   46  ...   58   95   25   
3    106   60   82   69   36   45   49   66   86   86  ...   13   19   17   
4     78   69   76   92   30   72   37   96   55   83  ...   18   22   96   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   48  104   16   84   96   51    2   15   19   58  ...   99   43   89   
296   54   29   38    8    1   46  105   54   72   46  ...   72   94   17   
297    3   85   78   96   63   93   31   89   76   90  ...   93   25   86   
298   93   82   94   45   98   54   22   39   37  100  ...   36    4   54   
299   38   24   99   58    5   64   38   36    8   60  ...   77   65  106   

     393  394  395  396  397  398  399  
0     98   77   17   39   64   46    9  
1     10   21    9   82    1   54   88  
2     76   68   35    2   79   32   88  
3     50    5   22  103   60    6   63  
4     59   48   99   87   50   33   54  
..   ...  ...  ...  ...  ...  ...  ...  
295    9   37  100   28   95    1   38  
296  106  101   95   60    6   69   46  
297    5   76   77  101  105   75   67  
298   50   57   59   28   92   33   64  
299   39   79   99   62    3   56    3  

[300 rows x 400 columns]

In [163]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')
# it will create a "test.csv" file.

In [164]:
arr = np.random.rand(3,4)

In [165]:
arr

array([[0.55358537, 0.57428375, 0.36738525, 0.63387398],
       [0.35673726, 0.71534037, 0.88140306, 0.18029071],
       [0.39628591, 0.59690446, 0.2146325 , 0.64509734]])

In [166]:
arr.reshape(6,-1)
# it become automatically of (6*2)

array([[0.55358537, 0.57428375],
       [0.36738525, 0.63387398],
       [0.35673726, 0.71534037],
       [0.88140306, 0.18029071],
       [0.39628591, 0.59690446],
       [0.2146325 , 0.64509734]])

In [167]:
arr1 = arr.reshape(6,-134353553435)

In [168]:
arr1

array([[0.55358537, 0.57428375],
       [0.36738525, 0.63387398],
       [0.35673726, 0.71534037],
       [0.88140306, 0.18029071],
       [0.39628591, 0.59690446],
       [0.2146325 , 0.64509734]])

In [169]:
arr1[1][1]
# it is like indexing as in the list

np.float64(0.6338739833592325)

In [170]:
arr1[2:5,1]

array([0.71534037, 0.18029071, 0.59690446])

In [171]:
arr = np.random.randint(1,100 , (5,5))

In [172]:
arr

array([[ 1, 49,  8, 25, 83],
       [60, 54, 67, 51, 31],
       [47, 67, 97, 52, 82],
       [32, 24, 70, 21, 16],
       [81, 80, 62, 54,  7]], dtype=int32)

In [173]:
arr[arr>50]

array([83, 60, 54, 67, 51, 67, 97, 52, 82, 70, 81, 80, 62, 54],
      dtype=int32)

In [174]:
arr

array([[ 1, 49,  8, 25, 83],
       [60, 54, 67, 51, 31],
       [47, 67, 97, 52, 82],
       [32, 24, 70, 21, 16],
       [81, 80, 62, 54,  7]], dtype=int32)

In [175]:
arr[2:4 , [1,2]]
# here 2:4 is for the rows selection and [1,2] is for column selection.

array([[67, 97],
       [24, 70]], dtype=int32)

In [176]:
arr[0][0] = 5000

In [177]:
arr

array([[5000,   49,    8,   25,   83],
       [  60,   54,   67,   51,   31],
       [  47,   67,   97,   52,   82],
       [  32,   24,   70,   21,   16],
       [  81,   80,   62,   54,    7]], dtype=int32)

In [178]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [179]:
arr1

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [180]:
arr2


array([[1, 2, 2],
       [2, 2, 1],
       [1, 2, 2]], dtype=int32)

In [181]:
arr1+arr2

array([[3, 3, 3],
       [4, 4, 3],
       [2, 3, 4]], dtype=int32)

In [182]:
arr1-arr2

array([[ 1, -1, -1],
       [ 0,  0,  1],
       [ 0, -1,  0]], dtype=int32)

In [183]:
arr1/arr2

array([[2. , 0.5, 0.5],
       [1. , 1. , 2. ],
       [1. , 0.5, 1. ]])

In [184]:
arr1 * arr2

array([[2, 2, 2],
       [4, 4, 2],
       [1, 2, 4]], dtype=int32)

In [185]:
arr1

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [186]:
arr2

array([[1, 2, 2],
       [2, 2, 1],
       [1, 2, 2]], dtype=int32)

In [188]:
arr1@arr2
# It will give the matrix multiplication

array([[ 5,  8,  7],
       [ 8, 12, 10],
       [ 5,  8,  7]], dtype=int32)

In [189]:
arr1/0

C:\Users\HP\AppData\Local\Temp\ipykernel_9800\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [190]:
arr1 +100

array([[102, 101, 101],
       [102, 102, 102],
       [101, 101, 102]], dtype=int32)

In [191]:
arr1**2

array([[4, 1, 1],
       [4, 4, 4],
       [1, 1, 4]], dtype=int32)

In [192]:
#Numpy – Broadcasting.

In [193]:
arr =np.zeros((4,4))

In [194]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [195]:
row = np.array([1,2,3,4])

In [196]:
row.shape



(4,)

In [197]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [198]:
row.T

array([1, 2, 3, 4])

In [199]:
col = np.array([[1,2,3,4]])

In [200]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [201]:
col

array([[1, 2, 3, 4]])

In [202]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [203]:
arr1 = np.random.randint(1,4 , (3,4))

In [204]:
arr1

array([[3, 1, 2, 1],
       [1, 2, 1, 1],
       [1, 3, 3, 3]], dtype=int32)

In [205]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        , 1.        ],
       [1.        , 1.73205081, 1.73205081, 1.73205081]])

In [206]:



np.exp(arr1)

array([[20.08553692,  2.71828183,  7.3890561 ,  2.71828183],
       [ 2.71828183,  7.3890561 ,  2.71828183,  2.71828183],
       [ 2.71828183, 20.08553692, 20.08553692, 20.08553692]])

In [207]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.30103   , 0.        ],
       [0.        , 0.30103   , 0.        , 0.        ],
       [0.        , 0.47712125, 0.47712125, 0.47712125]])